name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Format check
        run: npm run fmt:check
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Unit tests + coverage
        run: npm run test:cov
      - name: Ensure tests changed with src
        if: github.event_name == 'pull_request'
        run: npm run check:pr
      - name: Build site
        run: npm run build
      - name: Ensure dist is generated
        run: npm run check:dist
